[build-system]
requires = ["setuptools==68.2.2", "wheel==0.42.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Otimizações para builds no Render
zip-safe = false
include-package-data = true