services:
  - type: web
    name: futebol-predict
    runtime: python
    pythonVersion: "3.10.13"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: DATA_SOURCE
        value: scrape
      - key: FOOTAPI_KEY
        value: ${{FOOTAPI_KEY}}
    plan: free