services:
  - type: web
    name: futebol-predict
    runtime: python
    pythonVersion: "3.9.16"
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PIP_VERSION
        value: 23.0.1
      - key: SETUPTOOLS_VERSION
        value: 65.5.1
    plan: free