services:
  - type: web
    name: alpha-ai-football
    runtime: python
    python:
      version: "3.9.16"
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import init_db; init_db()"
    startCommand: gunicorn app:app
    envVars:
      - key: FOOTBALL_DATA_API_KEY
        description: "Chave para a API Football-Data.org"
      - key: ALTERNATIVE_FOOTBALL_API_KEY
        description: "Chave alternativa para API de futebol"
      - key: PYTHON_VERSION
        value: "3.9.16"