services:
  - type: web
    name: futebol-predict
    runtime: python
    pythonVersion: "3.10.13"  # Versão mais estável em 2025
    buildCommand: |
      python -m pip install --upgrade "setuptools<81.0.0" wheel
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FOOTBALL_DATA_API_KEY
        value: ${{FOOTBALL_DATA_API_KEY}}
      - key: DATA_SOURCE
        value: scrape
    plan: free