services:
  - type: web
    name: alpha-ai-football
    runtime: python
    python:
      version: "3.9.16"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm app:app
    envVars:
      - key: FOOTBALL_DATA_API_KEY
        description: "Chave da API Football-Data"
      - key: ALTERNATIVE_FOOTBALL_API_KEY
        description: "Chave alternativa (opcional)"
      - key: SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL
        value: "True"